// The conversation loop: streams Claude's reply, runs requested tools one at
// a time (edits are never run in parallel), feeds results back, and stops
// cleanly on user request. History is append-only (thinking blocks are
// passed back unchanged, as the API requires).

import { Emitter, truncate } from "../core/util.js";
import { ClaudeError, assistantContentForHistory } from "../claude/client.js";
import { addUsage } from "../claude/models.js";
import { toToolResultBlock } from "./registry.js";
import { buildSystemPrompt } from "./system-prompt.js";
import { StopToken } from "../executor/executor.js";
import { diffTimelines, fingerprintTimeline } from "./format.js";
import { ticksToSeconds } from "../core/time.js";

export class Agent extends Emitter {
  /**
   * @param {object} o
   * @param {import('../claude/client.js').ClaudeClient} o.client
   * @param {import('./registry.js').ToolRegistry} o.registry
   * @param {() => object} o.makeContext  returns the tool context for a turn
   * @param {object} o.settings SettingsStore
   */
  constructor({ client, registry, makeContext, settings, maxSteps = 60 }) {
    super();
    Object.assign(this, { client, registry, makeContext, settings, maxSteps });
    this.history = [];
    this.pendingNotes = [];
    this.busy = false;
    this.usage = null;
    this.system = buildSystemPrompt();
    this.lastTimelineFp = null;
    this.lastTimeline = null;
  }

  reset() {
    if (this.busy) throw new Error("Stop the current task first.");
    this.history = [];
    this.pendingNotes = [];
    this.usage = null;
    this.emit("reset");
  }

  addNote(text) {
    this.pendingNotes.push(text);
  }

  stop() {
    this.stopToken?.stop();
    this.abort?.abort();
    this.emit("stopping");
  }

  /** Build the non-user context note for this turn. */
  async contextNote(ctx) {
    const lines = ["[Panel context — generated by the plugin, not typed by the user]"];
    try {
      const pr = await ctx.host.project();
      lines.push(`Project: "${pr.name}"`);
      const tl = await ctx.host.readTimeline();
      const fp = fingerprintTimeline(tl);
      const change = this.lastTimeline && fp !== this.lastTimelineFp ? diffTimelines(this.lastTimeline, tl) : null;
      lines.push(`Active sequence: "${tl.sequence.name}" [${tl.sequence.id}] ${tl.sequence.fps}fps ${tl.sequence.width}x${tl.sequence.height}, ${ticksToSeconds(tl.sequence.endTicks).toFixed(2)}s, ${[...tl.tracks.video, ...tl.tracks.audio].reduce((a, t) => a + t.items.length, 0)} clips, In/Out ${tl.sequence.inOut ? "set" : "not set"}, ${tl.selection.length} selected`);
      if (change) lines.push(`⚠ The timeline changed since you last saw it (${change}). Re-read it before editing.`);
      this.lastTimeline = tl;
      this.lastTimelineFp = fp;
      ctx.state.lastTimeline = tl;
    } catch (e) {
      lines.push(`Premiere: ${e.message}`);
    }
    const s = this.settings;
    lines.push(`Work scope: ${s.get("analysisScope")}${s.get("analyzeFullSource") ? " + full source files" : " (only parts in scope)"} · Execution mode: ${s.get("executionMode")} · Helper: ${ctx.helper?.status?.state || "offline"}${ctx.host.capabilities ? ` · Premiere ${ctx.host.capabilities.version}` : ""}`);
    const m = ctx.memory.data;
    if (m.constraints.length || m.pins.length) lines.push(`Remembered rules: ${[...m.constraints.map((c) => c.label), ...m.pins.map((p) => `pinned: ${p.label}`)].slice(0, 20).join(" | ")}`);
    if (m.versions.length) lines.push(`Versions: ${m.versions.slice(-6).map((v) => `${v.id} "${v.name}"`).join(", ")}`);
    const favs = s.get("favoriteStyles");
    if (favs?.length) lines.push(`Favourite styles: ${favs.join(", ")}`);
    if (!this.history.length && m.summary) lines.push(`Earlier in this project: ${truncate(m.summary, 1500)}`);
    for (const n of this.pendingNotes.splice(0)) lines.push(n);
    return lines.join("\n");
  }

  /**
   * Send a user message and run the agent loop until Claude finishes.
   * @param {string} text
   * @param {{blocks?: object[]}} [extra] extra content blocks (e.g. attached images)
   */
  async send(text, extra = {}) {
    if (this.busy) throw new Error("Busy — wait for the current task or press Stop.");
    this.busy = true;
    this.stopToken = new StopToken();
    this.abort = new AbortController();
    const ctx = this.makeContext({ stop: this.stopToken, signal: this.abort.signal, userText: text });
    this.emit("busy", true);
    try {
      const note = await this.contextNote(ctx);
      const content = [{ type: "text", text: note }, ...(extra.blocks || []), { type: "text", text }];
      const last = this.history[this.history.length - 1];
      if (last && last.role === "user") last.content.push(...content); // pending tool results (turn ended for approval)
      else this.history.push({ role: "user", content });

      for (let step = 0; step < this.maxSteps; step++) {
        if (this.stopToken.stopped) break;
        this.emit("phase", { phase: step === 0 ? "thinking" : "continuing" });
        let msg;
        try {
          msg = await this.client.stream(
            {
              model: this.settings.get("model"),
              system: this.system,
              messages: this.history,
              tools: this.registry.definitions(),
              maxTokens: 32000,
              effort: this.settings.get("effort"),
              showThinking: this.settings.get("showThinking"),
            },
            {
              onStart: () => this.emit("assistant_start"),
              onText: (d) => this.emit("text", d),
              onThinking: (d) => this.emit("thinking", d),
              onToolStart: (b) => this.emit("tool_pending", { id: b.id, name: b.name }),
              onRetry: (r) => this.emit("retry", r),
              onFallback: (b) => this.emit("notice", `Served by fallback model ${b.to?.model || ""}`),
            },
            this.abort.signal
          );
        } catch (e) {
          if (e instanceof ClaudeError && e.kind === "aborted") {
            this.emit("notice", "Stopped.");
            break;
          }
          throw e;
        }
        this.usage = addUsage(this.usage, msg.usage);
        this.emit("usage", { turn: msg.usage, total: this.usage, model: msg.model });
        const content = assistantContentForHistory(msg.content);
        if (content.length) this.history.push({ role: "assistant", content });
        this.emit("assistant_end", { stopReason: msg.stop_reason });

        if (msg.stop_reason === "refusal") {
          this.emit("notice", `Claude declined this request${msg.stop_details?.category ? ` (${msg.stop_details.category})` : ""}. Rephrase or try another model.`);
          if (content.length && content.some((b) => b.type === "tool_use")) this.history.pop();
          break;
        }
        const toolUses = content.filter((b) => b.type === "tool_use");
        if (msg.stop_reason === "pause_turn") continue;
        if (!toolUses.length) {
          if (msg.stop_reason === "max_tokens") this.emit("notice", "The reply hit the length limit. Ask me to continue.");
          break;
        }
        // Run tools sequentially — edits must never race.
        const results = [];
        let endTurn = false;
        for (const tu of toolUses) {
          if (this.stopToken.stopped) {
            results.push(toToolResultBlock(tu.id, { isError: true, text: "Not run: the user pressed Stop." }));
            continue;
          }
          const inputErr = msg.toolInputErrors?.[tu.id] || (msg.stop_reason === "max_tokens" && tu === toolUses[toolUses.length - 1] ? "The tool input was cut off at the output limit. Re-issue a smaller call." : null);
          this.emit("tool_start", { id: tu.id, name: tu.name, input: tu.input });
          const r = inputErr ? { isError: true, text: inputErr } : await this.registry.run(tu.name, tu.input, ctx);
          this.emit("tool_end", { id: tu.id, name: tu.name, ok: !r.isError, text: r.text, images: r.images?.length || 0 });
          if (r.endTurn) endTurn = true;
          results.push(toToolResultBlock(tu.id, r));
        }
        this.history.push({ role: "user", content: results });
        if (this.stopToken.stopped || endTurn) break;
      }
    } finally {
      this.busy = false;
      this.emit("busy", false);
      this.emit("phase", { phase: "idle" });
    }
  }
}
