// مخطط قاعدة البيانات (PostgreSQL، المخطط store). كل ترحيل يُنفذ مرة واحدة بالترتيب ويُسجل رقمه في جدول meta.
// المبالغ المالية تُخزن كأعداد صحيحة بوحدة "السنت" (المبلغ × 100) لتجنب أخطاء الكسور.
// التواريخ نصوص UTC بصيغة 'YYYY-MM-DD HH:MM:SS' (تُقارن نصياً بشكل صحيح).

/** يُنفذ قبل الترحيلات */
export const PRELUDE = `CREATE TABLE IF NOT EXISTS meta (key TEXT PRIMARY KEY, value TEXT);`

export const MIGRATIONS: string[] = [
  /* 1 */ `
  -- دوال تحاكي datetime() في SQLite: تُرجع نص UTC بصيغة 'YYYY-MM-DD HH:MM:SS'
  CREATE OR REPLACE FUNCTION ts_parse(t text) RETURNS timestamp LANGUAGE sql STABLE AS $$
    SELECT CASE
      WHEN t IS NULL THEN NULL
      WHEN lower(t) = 'now' THEN (now() AT TIME ZONE 'UTC')
      WHEN t ~ '(Z|[+-][0-9][0-9]:?[0-9][0-9])$' THEN (t::timestamptz AT TIME ZONE 'UTC')
      ELSE t::timestamp
    END
  $$;
  CREATE OR REPLACE FUNCTION datetime(t text) RETURNS text LANGUAGE sql STABLE AS $$
    SELECT to_char(ts_parse(t), 'YYYY-MM-DD HH24:MI:SS')
  $$;
  CREATE OR REPLACE FUNCTION datetime(t text, m text) RETURNS text LANGUAGE sql STABLE AS $$
    SELECT to_char(ts_parse(t) + m::interval, 'YYYY-MM-DD HH24:MI:SS')
  $$;


  CREATE TABLE settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
  );

  CREATE TABLE counters (key TEXT PRIMARY KEY, value BIGINT NOT NULL);

  CREATE TABLE media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind TEXT NOT NULL CHECK (kind IN ('public','private')),
    path TEXT NOT NULL,
    ext TEXT NOT NULL,
    mime TEXT NOT NULL,
    width BIGINT,
    height BIGINT,
    sizes TEXT NOT NULL DEFAULT '[]',
    bytes BIGINT NOT NULL DEFAULT 0,
    original_name TEXT,
    purpose TEXT NOT NULL DEFAULT 'general',
    is_demo BIGINT NOT NULL DEFAULT 0,
    created_by BIGINT,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
  );

  CREATE TABLE admin_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    permissions TEXT NOT NULL DEFAULT '[]',
    active BIGINT NOT NULL DEFAULT 1,
    failed_logins BIGINT NOT NULL DEFAULT 0,
    locked_until TEXT,
    last_login_at TEXT,
    notif_seen_id BIGINT NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
  );

  CREATE TABLE sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash TEXT NOT NULL UNIQUE,
    user_id BIGINT NOT NULL REFERENCES admin_users(id) ON DELETE CASCADE,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    expires_at TEXT NOT NULL,
    last_seen_at TEXT NOT NULL DEFAULT (datetime('now')),
    ip TEXT,
    user_agent TEXT
  );
  CREATE INDEX idx_sessions_user ON sessions(user_id);

  CREATE TABLE audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    user_name TEXT,
    action TEXT NOT NULL,
    entity TEXT,
    entity_id TEXT,
    details TEXT,
    ip TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
  );
  CREATE INDEX idx_audit_created ON audit_log(created_at);

  CREATE TABLE rate_limits (
    key TEXT PRIMARY KEY,
    count BIGINT NOT NULL,
    reset_at BIGINT NOT NULL
  );

  CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL,
    title TEXT NOT NULL,
    body TEXT,
    link TEXT,
    permission TEXT NOT NULL DEFAULT 'orders',
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
  );

  CREATE TABLE appearance_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status TEXT NOT NULL CHECK (status IN ('draft','published','archived')),
    data TEXT NOT NULL,
    note TEXT,
    created_by BIGINT,
    created_by_name TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    published_at TEXT
  );

  CREATE TABLE pages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    content TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'published' CHECK (status IN ('draft','published')),
    show_in_footer BIGINT NOT NULL DEFAULT 1,
    system BIGINT NOT NULL DEFAULT 0,
    sort BIGINT NOT NULL DEFAULT 0,
    seo_title TEXT,
    seo_description TEXT,
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
  );

  CREATE TABLE faqs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question TEXT NOT NULL,
    answer TEXT NOT NULL,
    category TEXT,
    sort BIGINT NOT NULL DEFAULT 0,
    published BIGINT NOT NULL DEFAULT 1
  );

  CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    description TEXT,
    image_id BIGINT REFERENCES media(id) ON DELETE SET NULL,
    sort BIGINT NOT NULL DEFAULT 0,
    visible BIGINT NOT NULL DEFAULT 1,
    hidden_filters TEXT NOT NULL DEFAULT '[]',
    seo_title TEXT,
    seo_description TEXT,
    is_demo BIGINT NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
  );

  CREATE TABLE tag_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    kind TEXT NOT NULL DEFAULT 'custom' CHECK (kind IN ('age','occasion','custom')),
    show_in_filters BIGINT NOT NULL DEFAULT 1,
    sort BIGINT NOT NULL DEFAULT 0
  );

  CREATE TABLE tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL REFERENCES tag_groups(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    description TEXT,
    image_id BIGINT REFERENCES media(id) ON DELETE SET NULL,
    sort BIGINT NOT NULL DEFAULT 0,
    visible BIGINT NOT NULL DEFAULT 1
  );

  CREATE TABLE size_guides (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    intro TEXT,
    columns TEXT NOT NULL DEFAULT '[]',
    rows TEXT NOT NULL DEFAULT '[]',
    notes TEXT,
    image_id BIGINT REFERENCES media(id) ON DELETE SET NULL,
    is_demo BIGINT NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
  );

  CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL DEFAULT 'simple' CHECK (type IN ('simple','variable','bundle')),
    sku TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    short_description TEXT,
    description TEXT,
    category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
    status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','published','archived')),
    price BIGINT NOT NULL DEFAULT 0,
    sale_price BIGINT,
    sale_starts_at TEXT,
    sale_ends_at TEXT,
    track_stock BIGINT NOT NULL DEFAULT 1,
    stock BIGINT NOT NULL DEFAULT 0,
    manual_availability TEXT NOT NULL DEFAULT 'in_stock' CHECK (manual_availability IN ('in_stock','out_of_stock')),
    low_stock_threshold BIGINT,
    max_per_order BIGINT,
    options TEXT NOT NULL DEFAULT '[]',
    material TEXT,
    care_instructions TEXT,
    size_guide_id BIGINT REFERENCES size_guides(id) ON DELETE SET NULL,
    set_contents TEXT NOT NULL DEFAULT '[]',
    pieces_count BIGINT,
    prep_days_min BIGINT,
    prep_days_max BIGINT,
    gift_wrap_eligible BIGINT NOT NULL DEFAULT 1,
    personalization TEXT,
    seo_title TEXT,
    seo_description TEXT,
    search_text TEXT NOT NULL DEFAULT '',
    is_demo BIGINT NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    published_at TEXT
  );
  CREATE INDEX idx_products_status ON products(status);
  CREATE INDEX idx_products_category ON products(category_id);

  CREATE TABLE product_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    media_id BIGINT NOT NULL REFERENCES media(id),
    alt TEXT,
    option_value TEXT,
    sort BIGINT NOT NULL DEFAULT 0
  );
  CREATE INDEX idx_product_images_product ON product_images(product_id);

  CREATE TABLE variants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    sku TEXT NOT NULL UNIQUE,
    option1 TEXT,
    option2 TEXT,
    option3 TEXT,
    price BIGINT,
    sale_price BIGINT,
    stock BIGINT NOT NULL DEFAULT 0,
    active BIGINT NOT NULL DEFAULT 1,
    sort BIGINT NOT NULL DEFAULT 0
  );
  CREATE INDEX idx_variants_product ON variants(product_id);

  CREATE TABLE product_tags (
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    tag_id BIGINT NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
    PRIMARY KEY (product_id, tag_id)
  );

  CREATE TABLE product_relations (
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    related_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    kind TEXT NOT NULL CHECK (kind IN ('related','complementary')),
    sort BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (product_id, related_id, kind)
  );

  CREATE TABLE bundle_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bundle_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES products(id),
    variant_id BIGINT REFERENCES variants(id) ON DELETE SET NULL,
    qty BIGINT NOT NULL DEFAULT 1 CHECK (qty > 0),
    sort BIGINT NOT NULL DEFAULT 0
  );
  CREATE INDEX idx_bundle_items_bundle ON bundle_items(bundle_id);

  CREATE TABLE stock_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT,
    variant_id BIGINT,
    sku TEXT,
    product_name TEXT,
    change BIGINT NOT NULL,
    stock_after BIGINT,
    reason TEXT NOT NULL,
    order_id BIGINT,
    user_id BIGINT,
    user_name TEXT,
    note TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
  );
  CREATE INDEX idx_movements_product ON stock_movements(product_id, created_at);

  CREATE TABLE gift_wraps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    price BIGINT NOT NULL DEFAULT 0,
    image_id BIGINT REFERENCES media(id) ON DELETE SET NULL,
    active BIGINT NOT NULL DEFAULT 1,
    sort BIGINT NOT NULL DEFAULT 0,
    is_demo BIGINT NOT NULL DEFAULT 0
  );

  CREATE TABLE shipping_zones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    country TEXT NOT NULL DEFAULT 'اليمن',
    cities TEXT NOT NULL DEFAULT '[]',
    fee BIGINT NOT NULL DEFAULT 0,
    free_shipping_eligible BIGINT NOT NULL DEFAULT 1,
    eta_text TEXT,
    active BIGINT NOT NULL DEFAULT 1,
    sort BIGINT NOT NULL DEFAULT 0,
    is_demo BIGINT NOT NULL DEFAULT 0
  );

  CREATE TABLE transfer_methods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT NOT NULL DEFAULT 'bank' CHECK (type IN ('bank','wallet','exchange','other')),
    beneficiary TEXT NOT NULL,
    account_number TEXT NOT NULL,
    extra_info TEXT,
    currency TEXT,
    instructions TEXT,
    qr_media_id BIGINT REFERENCES media(id) ON DELETE SET NULL,
    active BIGINT NOT NULL DEFAULT 1,
    sort BIGINT NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
  );

  CREATE TABLE coupons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    description TEXT,
    type TEXT NOT NULL CHECK (type IN ('percent','fixed')),
    value BIGINT NOT NULL,
    min_order BIGINT,
    max_discount BIGINT,
    starts_at TEXT,
    ends_at TEXT,
    usage_limit BIGINT,
    per_customer_limit BIGINT,
    category_ids TEXT NOT NULL DEFAULT '[]',
    product_ids TEXT NOT NULL DEFAULT '[]',
    combine_with_sale BIGINT NOT NULL DEFAULT 1,
    active BIGINT NOT NULL DEFAULT 1,
    is_demo BIGINT NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
  );

  CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    country TEXT,
    city TEXT,
    area TEXT,
    address TEXT,
    notes TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    last_order_at TEXT
  );

  CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number TEXT NOT NULL UNIQUE,
    token TEXT NOT NULL UNIQUE,
    idempotency_key TEXT UNIQUE,
    customer_id BIGINT REFERENCES customers(id),
    customer_name TEXT NOT NULL,
    customer_phone TEXT NOT NULL,
    customer_country TEXT,
    customer_city TEXT,
    customer_area TEXT,
    customer_address TEXT,
    customer_landmark TEXT,
    customer_map_url TEXT,
    notes TEXT,
    fulfillment TEXT NOT NULL CHECK (fulfillment IN ('delivery','pickup')),
    zone_id BIGINT,
    zone_name TEXT,
    eta_text TEXT,
    is_gift BIGINT NOT NULL DEFAULT 0,
    recipient_name TEXT,
    recipient_phone TEXT,
    recipient_country TEXT,
    recipient_city TEXT,
    recipient_area TEXT,
    recipient_address TEXT,
    gift_message TEXT,
    hide_prices BIGINT NOT NULL DEFAULT 0,
    gift_wrap_id BIGINT,
    gift_wrap_name TEXT,
    subtotal BIGINT NOT NULL,
    discount BIGINT NOT NULL DEFAULT 0,
    wrap_fee BIGINT NOT NULL DEFAULT 0,
    personalization_fee BIGINT NOT NULL DEFAULT 0,
    shipping_fee BIGINT NOT NULL DEFAULT 0,
    total BIGINT NOT NULL,
    currency TEXT NOT NULL,
    currency_symbol TEXT NOT NULL,
    coupon_id BIGINT,
    coupon_code TEXT,
    transfer_method_id BIGINT,
    transfer_method_name TEXT,
    status TEXT NOT NULL DEFAULT 'pending'
      CHECK (status IN ('pending','confirmed','preparing','shipped','completed','cancelled')),
    payment_status TEXT NOT NULL DEFAULT 'awaiting_transfer'
      CHECK (payment_status IN ('awaiting_transfer','under_review','partially_paid','paid','needs_review','partially_refunded','refunded')),
    stock_state TEXT NOT NULL DEFAULT 'reserved' CHECK (stock_state IN ('reserved','committed','released','none')),
    reservation_expires_at TEXT,
    reservation_released_at TEXT,
    prep_days_min BIGINT,
    prep_days_max BIGINT,
    shipping_carrier TEXT,
    tracking_number TEXT,
    tracking_url TEXT,
    shipped_at TEXT,
    completed_at TEXT,
    cancelled_at TEXT,
    cancel_reason TEXT,
    payment_confirmed_by BIGINT,
    payment_confirmed_by_name TEXT,
    payment_confirmed_at TEXT,
    ip_hash TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
  );
  CREATE INDEX idx_orders_status ON orders(status);
  CREATE INDEX idx_orders_payment ON orders(payment_status);
  CREATE INDEX idx_orders_created ON orders(created_at);
  CREATE INDEX idx_orders_phone ON orders(customer_phone);
  CREATE INDEX idx_orders_coupon ON orders(coupon_id);

  CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    product_id BIGINT,
    variant_id BIGINT,
    product_type TEXT NOT NULL,
    name TEXT NOT NULL,
    sku TEXT NOT NULL,
    options TEXT NOT NULL DEFAULT '[]',
    image TEXT,
    unit_price BIGINT NOT NULL,
    compare_price BIGINT,
    qty BIGINT NOT NULL,
    line_total BIGINT NOT NULL,
    personalization_label TEXT,
    personalization_text TEXT,
    personalization_fee BIGINT NOT NULL DEFAULT 0,
    components TEXT NOT NULL DEFAULT '[]',
    returned_qty BIGINT NOT NULL DEFAULT 0
  );
  CREATE INDEX idx_order_items_order ON order_items(order_id);
  CREATE INDEX idx_order_items_product ON order_items(product_id);

  CREATE TABLE order_stock_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    order_item_id BIGINT NOT NULL REFERENCES order_items(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL,
    variant_id BIGINT,
    sku TEXT,
    name TEXT,
    qty BIGINT NOT NULL,
    deducted BIGINT NOT NULL DEFAULT 0
  );
  CREATE INDEX idx_stock_lines_order ON order_stock_lines(order_id);

  CREATE TABLE order_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    media_id BIGINT NOT NULL REFERENCES media(id),
    label TEXT,
    uploaded_by BIGINT,
    uploaded_by_name TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
  );

  CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    method_id BIGINT,
    method_name TEXT,
    amount BIGINT NOT NULL,
    transfer_date TEXT,
    reference TEXT,
    sender_name TEXT,
    notes TEXT,
    attachment_id BIGINT REFERENCES order_attachments(id) ON DELETE SET NULL,
    recorded_by BIGINT,
    recorded_by_name TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
  );
  CREATE INDEX idx_payments_order ON payments(order_id);
  CREATE INDEX idx_payments_reference ON payments(reference);

  CREATE TABLE refunds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    amount BIGINT NOT NULL,
    method TEXT,
    reference TEXT,
    reason TEXT,
    created_by BIGINT,
    created_by_name TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
  );

  CREATE TABLE order_returns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    items TEXT NOT NULL,
    reason TEXT,
    restocked BIGINT NOT NULL DEFAULT 0,
    created_by BIGINT,
    created_by_name TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
  );

  CREATE TABLE order_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    user_id BIGINT,
    user_name TEXT,
    body TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
  );

  CREATE TABLE order_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    type TEXT NOT NULL,
    message TEXT NOT NULL,
    data TEXT,
    public BIGINT NOT NULL DEFAULT 0,
    user_id BIGINT,
    user_name TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
  );
  CREATE INDEX idx_order_events_order ON order_events(order_id);

  -- أرقام المنتجات وأسماء المستخدمين والكوبونات فريدة دون اعتبار لحالة الأحرف
  CREATE UNIQUE INDEX idx_products_sku_ci ON products (upper(sku));
  CREATE UNIQUE INDEX idx_variants_sku_ci ON variants (upper(sku));
  CREATE UNIQUE INDEX idx_coupons_code_ci ON coupons (upper(code));
  CREATE UNIQUE INDEX idx_admin_users_username_ci ON admin_users (lower(username));
  CREATE INDEX idx_order_items_variant ON order_items(variant_id);
  CREATE INDEX idx_customers_name ON customers(name);

  -- ملفات الصور والسندات (محتوى ثنائي). العامة تُخدم عبر /media مع تخزين مؤقت طويل،
  -- والخاصة (السندات) لا تُخدم إلا لمستخدم مخوّل.
  CREATE TABLE media_blobs (
    key TEXT PRIMARY KEY,
    media_id BIGINT REFERENCES media(id) ON DELETE CASCADE,
    mime TEXT NOT NULL,
    bytes BIGINT NOT NULL,
    data BYTEA NOT NULL,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
  );
  CREATE INDEX idx_media_blobs_media ON media_blobs(media_id);

  -- نسخ احتياطية للبيانات (JSON مضغوط) داخل قاعدة البيانات، تُنزّل من لوحة التحكم
  CREATE TABLE backups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    kind TEXT NOT NULL DEFAULT 'manual',
    bytes BIGINT NOT NULL,
    data BYTEA NOT NULL,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
  );
  `,
  /* 2 */ `
  -- دور الصورة: rail = صورة الشماعة (الأمام، يُفضل بخلفية شفافة، لا تظهر في المعرض)، back = صورة الخلف
  ALTER TABLE product_images ADD COLUMN role TEXT CHECK (role IN ('rail','back'));
  `,
]
